Add rate limiting
CFC-Servers/cfc_streamcore pull request #6
Opened 2021-02-19 08:42 UTC by brandonsturgeon

2021-02-19 23:33 UTC, samuelWilliams99 requested changes

2021-02-19 23:33 UTC, samuelWilliams99 commented on lua/entities/gmod_wire_expression2/core/custom/streamcore.lua
> +    if not throttles then ent.streamcoreThrottle = {} end
gotta assign throttles to this new table else it'll still be nil when you set it to CurTime
```suggestion
    if not throttles then
        throttles = {}
        ent.streamcoreThrottle = throttles
    end
```

2021-02-19 23:33 UTC, samuelWilliams99 commented on lua/entities/gmod_wire_expression2/core/custom/streamcore.lua
> +        ent.streamcoreThrottle = {}
Same as before

2021-02-19 23:33 UTC, samuelWilliams99 commented on lua/entities/gmod_wire_expression2/core/custom/streamcore.lua
> +    setLastUse(self, "streamVolume")
```suggestion
    setLastUse( self, "streamVolume" )
```

2021-02-19 23:33 UTC, samuelWilliams99 commented on lua/entities/gmod_wire_expression2/core/custom/streamcore.lua
> +    setLastUse(self, "streamRadius")
```suggestion
    setLastUse( self, "streamRadius" )
```

2021-02-20 04:45 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/streamcore.lua
> +local stringTrim = string.Trimp
```suggestion
local stringTrim = string.Trim
```

2021-02-20 04:46 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/streamcore.lua
> +        ent.streamcoreThrottle = {}
```suggestion
        throttles = {}
        ent.streamcoreThrottle = throttles
```

2021-02-20 11:05 UTC, samuelWilliams99 approved these changes, later dismissed

2021-02-22 06:39 UTC, merged

2021-02-22 06:39 UTC, brandonsturgeon commented
Tested, works as expected 👍 

Going to throw it on the server and let the players bug test it :^)